### ISSUE TITLE
Bug since when last update

### ISSUE THREAD

**Issue by n0f4c3** [inbasic/ignotifier#426]
example : Youtube Video does not open instead Downloading picture Video
Please fix!
(Use Firefox 49.0.1 )
(Use Gmail Notifier 0.67)

**Comment by inbasic** [comment]
Please send me a sample email with this issue.

**Comment by n0f4c3** [comment]
ok email send

**Comment by inbasic** [comment]
Thanks! It is now fixed on the dev channel. To try download https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true then open a browser tab for "About:debugging". Turn the developer mode on and point the browse button to the downloaded XPI

**Comment by n0f4c3** [comment]
thank you video accessible again but email still appears strangely. picture above
youtube is not the problem i tested an old version 0.65 of the extension and walk properly

**Comment by inbasic** [comment]
The color issue should have been fixed on https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

Thanks for the report.

**Comment by trlkly** [comment]
@inbasic: you don't actually have to turn developer mode on. Just use the "Load Temporary Addon" button and find the XPI file.
