### ISSUE TITLE
Translation of the addon

### ISSUE THREAD

**Issue by CaTzil** [inbasic/ignotifier#61]
you wanted to translate the addon to native languages of FF.

so, i suggest to use this service, https://www.transifex.com/
its allow you mange all the translations and users can translate the addon to chosen language.

**Comment by odie2** [comment]
Hello,
It is really sad that you again forgot about Polish language from Transifex and it seems like Transifex is little outdated...
Greetings

**Comment by inbasic** [comment]
Hi, 

Right, there was some problems with the locale. I'll fix this soon and submit a new version to Transifex.

**Comment by inbasic** [comment]
I want to start working on the translation bugs. Can somebody summarize the bugs we have?

**Comment by odie2** [comment]
What exactly bugs you mean?
There are no truly bugs, only missing phrases or translations.

Desktop notifications phrases are no translated. Toolbar box the same. Also at settings phrases are missing texts - for that you should the best download Polish current translation and replace it with you current. Then you could check what texts are missing.

**Comment by inbasic** [comment]
I wrote a very simple converter to have the JSON translation files recognizable by Firefox.
The instruction is added to `multi-browser` channel if you would like to do the conversion yourself,
https://github.com/inbasic/ignotifier/tree/multi-browser

Please somebody push the new EN locale to transifex.

@odie2 except the panel strings, the rest of the extension is localized. So if there is anything unlocalized we need to fix. In my test, both toolbar description and desktop notifications were localized. To test, I just replaced the EN JSON with one of the others, so I haven't really changed the browser language.

@CaTzil @odie2 @Nekomajin42 @KissDaniGH please check your locale files in https://github.com/inbasic/ignotifier/tree/multi-browser/src.safariextension/locale once to make sure the encoding is fine. These are auto-generated files.

After the new translations are ready, I'll pack the extension so that you guys could try it in both Chrome and Firefox browsers.

**Comment by KissDaniGH** [comment]
"please check your locale files in..." hu-HU seems ok.

**Comment by odie2** [comment]
@inbasic 
with version 0.5.3 (https://addons.opera.com/pl/extensions/details/gmail-notifier/)
and outdated translation from Transifex ("Download for use" and rename it to "messages.json"),
placed in "en" or even in "pl" (%appdata%/Opera Software/Opera Developer/Extensions\[key]\0.5.3_0\_locales) - I have following effect:
http://maciej.kuzniczysko.pl/images/gmailnotifier1.jpg

Also still missing phrases from EN in Transifex.

**Comment by inbasic** [comment]
@odie2 The toolbar panel is still not localized. Beside the panel everything else (like toolbar button's tooltip, desktop notifications, options page, ...) should be localized though.

> Also still missing phrases from EN in Transifex.

I still have no access to Transifex. If you have please update the EN JSON.

**Comment by inbasic** [comment]
Anybody has access to the En locale on Transifex? If so would you please update the locale

**Comment by KissDaniGH** [comment]
not me but just sent a join request

**Comment by CaTzil** [comment]
What is the updated file of the en locale?

**Comment by inbasic** [comment]
@CaTzil https://github.com/inbasic/ignotifier/tree/multi-browser/src.safariextension/_locales/en

**Comment by odie2** [comment]
Not sure that this is Polish issue only for me or something else.
With previous version "Download for use" from Transifex I had no problem.
Now instead phrases I see only blank space.
Copied content to original messages.json (UNIX -> Dos\Windows), changed \" to ', removed \n
and still the same issue.
Tested with 5.3 in Opera, for "en" and "pl" catalog in extension.

Please check it before release.

![notifier](https://cloud.githubusercontent.com/assets/9401878/6850154/c3e4c550-d3d7-11e4-8171-a612370c2953.jpg)

**Comment by CaTzil** [comment]
@inbasic, i`ve updated the English source file.

**Comment by inbasic** [comment]
@CaTzil Thanks

@odie2 there was something wrong with the En locale. It is now fixed.

Guys I updated the locales in the `multi-borwser` channel. All the locales are up to date for Firefox, Chrome, Opera and Safari,

[Chrome, Opera, Safari] https://github.com/inbasic/ignotifier/tree/multi-browser/src.safariextension/_locales
[Firefox] https://github.com/inbasic/ignotifier/tree/multi-browser/src.safariextension/locale

Please try the latest beta version on both Firefox and Chrome to make sure your locale file works fine. For Firefox you just need to download the XPI file from https://github.com/inbasic/ignotifier/tree/multi-browser/src.safariextension/executables. Then drag&drop it into your browser. For Chrome/Opera, download the `multi-borwser` channel. Then open extensions manager and check the developer mode. Now press load unpack extension and point it to `./src.safariextension`.

**Comment by odie2** [comment]
@inbasic "The toolbar panel is still not localized. Beside the panel everything else (like toolbar button's tooltip, desktop notifications, options page, ...) should be localized though."

Desktop notifications still not fully translated (left bottom edge of screen), even with replacing messages.json in "en".
Also "From", "Title", "Summary" does not exists in translation.

![image](https://cloud.githubusercontent.com/assets/9401878/6871899/1a72af30-d4a6-11e4-8820-9d38098447b6.png)

**Comment by odie2** [comment]
And note for localization inside panel - if you just do not know how do it, check for example "Translator" extension (https://addons.opera.com/pl/extensions/details/translator/) - it provide the same panel (guessed from icon toolbar arrow to panel).

**Comment by inbasic** [comment]
> Note that "From", "Title", "Summary" does not exists in translation.

You need to manually fix the notification string from Settings,
![screen shot 2015-03-28 at 10 38 26](https://cloud.githubusercontent.com/assets/351062/6879992/de7f3c00-d536-11e4-9ab3-9abbcdbace64.png)

> And note for localization inside panel - if you just do not know how do it, check for example "Translator" 

I know how to localize the panel, the problem is the length of the translated strings. We need to find a more clever approach to implement the tooltips,
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/data/popup/index.css#L297-L323
That is the main reason why the panel is not yet localized.

**Comment by odie2** [comment]
Hmm so you should add default phrase for desktop notification to localization. This is very often did in many programs. If user is starting first time in certain language then he have native localization. If not, he have to do it manually.

I will look later for those length. Maybe I will find any css trick. Tooltips I saw somewhere.

**Comment by inbasic** [comment]
> Hmm so you should add default phrase for desktop notification to localization. This is very often did in many programs. If user is starting first time in certain language then he have native localization. If not, he have to do it manually.

Fixed,

Guys please update your locales,
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/_locales/en/messages.json#L79-L81

@CaTzil please add me to the En locale at Transifex

**Comment by CaTzil** [comment]
Done

**Comment by yfdyh000** [comment]
* The `likey` of "options_notifications_25 = In safari most likey the default sound notifications are not playing properly, if so use a custom sound file as your notification." needs an explanation or improve, it seems not a common English word, and the `safari` may need to `Safari`.
* I see a `settingsfff` ("popup_settings") on [Transifex strings](https://www.transifex.com/projects/p/gmail-notifier-addon/viewstrings/#en/messagesjson/42187078?q=settingsfff), what is that?
* "options_seconds = seconds" and "options_minutes = minutes" is needs be dispatch to those strings, because word order problem in various language and the `.` also needs to be localized (to `。` or none in Chinese).

**Comment by inbasic** [comment]
> The likey of "options_notifications_25 = In safari most likey the

fixed, https://github.com/inbasic/ignotifier/commit/840e2d060488edbdea5d5a0b081c0d06a6851911

> I see a settingsfff ("popup_settings") on Transifex strings, what is that?

fixed, https://github.com/inbasic/ignotifier/commit/d3e5900eb281958bfa6c8d751f9f313e007a8a4b

> And, any views for localization the "Gmail™ notifier" name, or should to keep it? why does it change to lowercase "notifier" instead of the "Notifier", I can to change it?

I would say keep the name as it is. It would be easier for users to find the extension in the stores and Yes, it should be capitalized, `Gmail™ Notifier`

> "options_seconds = seconds" and "options_minutes = minutes" is needs be dispatch to those strings, because word order problem in various language and the . also needs ..

Fixed,
https://github.com/inbasic/ignotifier/commit/3a7200833a763ee5781247a448d39b3254a97cc7

Guys please update your locales based on the commits.

@CaTzil I still have no access to the En locale, please add my email, inb[dot]cor[at]gmail[dot]com

**Comment by inbasic** [comment]
Guys locales are updated from transifex.com,
https://github.com/inbasic/ignotifier/commit/c0cc01a8f4287df42845251e7a1bb8fdbedbd8ca

Please check your locale in both Firefox and Chrome and let me know if there is any problem,
Latest Firefox built, https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

**Comment by yfdyh000** [comment]
* Please, zh_CN to zh-CN.
* `Options - Gmail™ notifier` and `Gmail notifier default alert`, "notifier" to "Notifier".
* `Available keys:` to `Available variables:`, "keys" like Keyboard shortcut (hotkey).
* `and` of `[author_name], [author_email], [title] and [summary].` is need to be localized.
* `unknown` and the `.` is needs to be localized.
* `.` after `Volume of the sound notification is` is need to allow localization.
* Maybe should remove the '.' in `Support keyboard shortcuts on the toolbar panel.`
* `tray.permanent` no label.

**Comment by inbasic** [comment]
@yfdyh000 are they fixed?

**Comment by yfdyh000** [comment]
* https://github.com/inbasic/ignotifier/blob/6ebd6e70967b1bd708a348c8dfc550274195972d/src.safariextension/lib/config.js#L229 no get localized string.
* Show localized add-on description in Add-ons Manger.

**Comment by inbasic** [comment]
@yfdyh000 first one is fixed, but the second one is not yet doable, see https://bugzilla.mozilla.org/show_bug.cgi?id=661083

**Comment by inbasic** [comment]
Guys I need to release a new version today. Please update your locales as soon as possible. `pl`, `nl`, and `he` locales need update.

**Comment by odie2** [comment]
Opened new issue with translations of description for Opera addons page: #313

**Comment by odie2** [comment]
> https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/data/popup/index.css#L297-L323
> That is the main reason why the panel is not yet localized.

@inbasic 

Hi,
wouldn't it's helpful?
http://community.sitepoint.com/t/css-tooltip-how-to-auto-center-over-element/22747/23
Greetings

**Comment by inbasic** [comment]
Guys I am closing this. Please open new bug reports if we still have issues. BTW, please check  https://www.transifex.com/ for the new updates.
